config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :announcements
  devise_for :users
  root 'announcements#index'
  resources :users do
    member do
      get :confirm_email
      get :announcements
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, Announcement, user_id: user.id
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/announcement.rb
# frozen_string_literal: true

class Announcement < ApplicationRecord
  include AASM

  VALID_TYPES = %w[Buy Sell Exchange].freeze

  belongs_to :user
  has_one_attached :image
  paginates_per 6
  scope :desc_order, -> { order(created_at: :desc) }
  scope :published, -> { where(status: 4) }

  validates :title, presence: true
  validates :content, presence: true
  validates :announcement_type, presence: true

  enum status: {
    draft: 0,
    ready_to_publish: 1,
    approved: 2,
    rejected: 3,
    published: 4,
    archived: 5
  }

  aasm column: :status, enum: true do
    state :draft, initial: true
    state :ready_to_publish, :approved, :rejected, :published, :archived

    event :send_to_moderate do
      transitions from: :draft, to: :ready_to_publish
    end

    event :approve do
      transitions from: :ready_to_publish, to: :approved
    end

    event :reject do
      transitions from: :ready_to_publish, to: :rejected
    end

    event :publish do
      transitions from: :approved, to: :published
    end

    event :refact do
      transitions from: :rejected, to: :draft
    end

    event :archive do
      transitions from: :published, to: :archived
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :announcements, dependent: :destroy
end

app/controllers/announcements_controller.rb
# frozen_string_literal: true

class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: %i[show edit update destroy]
  ITEMS_PER_PAGE = 10

  def index
    @announcements = Announcement.published.includes(image_attachment: :blob)
                                 .page(params[:page]).per(ITEMS_PER_PAGE).desc_order
  end

  def show
    return unless @announcement.rejected?

    flash[:notice] = t('flashes.reject_notice')
  end

  def new
    @announcement = Announcement.new(user_id: current_user.id)
  end

  def edit; end

  def create
    @announcement = current_user.announcements.new(announcement_params)
    @announcement.send_to_moderate if params[:post_button].present?
    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: t('announcements.notices.created') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        status_definition
        format.html { redirect_to @announcement, notice: t('announcements.notices.updated') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: t('announcements.notices.deleted') }
    end
  end

  private

  def set_announcement
    @announcement = Announcement.find(params[:id])
  end

  def announcement_params
    params.require(:announcement).permit(:title, :content, :announcement_type, :status, :phone, :image, :post_button)
  end

  def status_definition
    @announcement.refact! if @announcement.rejected?
    @announcement.send_to_moderate! if params[:post_button].present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in)
  end

  private

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    before_action :configure_sign_in_params, only: [:create]

    protected

    def configure_sign_in_params
      devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def announcements
    @announcements = User.find(params[:id]).announcements.includes(image_attachment: :blob)
  end
end

app/helpers/announcements_helper.rb
# frozen_string_literal: true

module AnnouncementsHelper
  def draft_or_rejected(announcement)
    announcement.draft? || announcement.rejected?
  end
end

app/views/announcements/_form.html.erb
<%= form_with(model: announcement, local: true) do |form| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.prohibited_from_being_saved') %>:</h2>

      <ul>
        <% announcement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, t('announcements.fields.title') %>:
    <%= form.text_field :title, {class: 'form-control', autofocus: true} %>
  </div>
  <br>

  <div class="field">
    <%= form.label :content, t('announcements.fields.content') %>:
    <%= form.text_area :content, {class: 'form-control'} %>
  </div>
  <br>

  <div class="field">
    <%= form.label :announcement_type, t('announcements.fields.type') %>:
    <%= form.select :announcement_type, Announcement::VALID_TYPES.map{ |type| [t("announcements.types.#{type.downcase}"), type]}, {}, {:class => 'form-control'} %>
  </div>
  <br>

  <div class="field phone-field">
    <%= form.label :phone, t('announcements.fields.phone') %>:<br>
    <%= form.telephone_field :phone, {placeholder: '+375(XX)-XXX-XX-XX', class: 'form-control'} %>
  </div>

  <div class="field">
    <%= form.label :image, t('announcements.fields.image') %>:&nbsp
    <%= form.file_field :image %>
  </div>

<div class="flex-buttons">
  <% if draft_or_rejected(@announcement) %>
    <div class="actions">
      <%= form.submit t('announcements.buttons.post'), {name: 'post_button', class: 'btn btn-success'} %>
    </div>
    <div class="actions">
      <%= form.submit t('announcements.buttons.save_draft'), class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>
<% end %>

app/views/announcements/edit.html.erb
<h2><%= t('announcements.titles.edit_announcement') %></h2>

<%= render 'form', announcement: @announcement %>

<%= link_to t('announcements.buttons.show'), @announcement %> |
<%= link_to t('announcements.buttons.back'), :back %>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>
<h2><%= t('announcements.titles.announcements') %></h2><br>

    <% @announcements.each do |announcement| %>
      <div class="media">
        <div class="product-img">
          <%= image_tag(announcement.image) if announcement.image.attached? %>
        </div>
        <div class="media-body">
          <%= announcement.title %><br>
          <span class="card-subtitle mb-2 text-muted"><%= announcement.content.truncate(100, separator: ' ') %></span><br>
          <i><%= t("announcements.types.#{announcement.announcement_type.downcase}") %></i><br>
          <%= announcement.user_id %><br>
          <div class="d-flex justify-content-between">
            <%= link_to t('announcements.buttons.show'), announcement %>
            <%= announcement.created_at.strftime("%d.%m.%Y") %>
          </div>
        </div>
      </div>
    <% end %>
<br>
<span class="pagination justify-content-center">
  <%= paginate @announcements, theme: 'twitter-bootstrap-4' %>
</span>

app/views/announcements/new.html.erb
<h2><%= t('announcements.titles.new_announcement') %></h2>

<%= render 'form', announcement: @announcement %>

<%= link_to t('announcements.buttons.back'), :back %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @announcement.title %>
</p>

<div class="show-image">
	<%= link_to image_tag(@announcement.image), announcements_path if @announcement.image.attached? %>	
</div>


<p>
  <strong><%= t('announcements.fields.content') %>:</strong>
  <%= @announcement.content %>
</p>
  
<p>
  <strong><%= t('announcements.fields.type') %>:</strong>
  <%= t("announcements.types.#{@announcement.announcement_type.downcase}") %>
</p>

<p>
  <strong><%= t('announcements.fields.author') %>:</strong>
  <%= @announcement.user_id  %>
</p>

<p>
  <strong><%= t('announcements.fields.phone') %>:</strong>
  <%= @announcement.phone %>
</p>

<% if draft_or_rejected(@announcement) %>
  <% if can? :update, @announcement %>
  	<%= link_to t('announcements.buttons.edit'), edit_announcement_path(@announcement) %> |
  <% end %>
<% elsif @announcement.ready_to_publish? %>
  <p><b><%= t('confirm_messages.on_moderation_message') %></b></p>
<% end %>

<% if can? :delete, @announcement %>
  <%= link_to t('announcements.buttons.destroy'), @announcement, method: :delete, 
              data: { confirm: t('confirm_messages.confirm_delete') } %> | 
<% end %>

<%= link_to t('announcements.buttons.back'), :back %>

app/views/layouts/_footer.html.erb
<footer class="container">
	<hr>
	<p>Projectads on Rails 2020-2021</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal home-link"><%= link_to 'ProjectAds', root_path %></h5>
    <% if user_signed_in? %>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark">
          <%= link_to t('announcements.buttons.new_announcement'), new_announcement_path %>
        </span>
        <span class="p-2 text-dark">
        <%= link_to t('announcements.buttons.my_announcements'), announcements_user_path(current_user, @announcement) %>
        </span>
      </nav>
      <button class="btn btn-outline-primary">
        <%= link_to t('announcements.buttons.log_out'), destroy_user_session_path, :method => :delete %>
      </button>
    <% else %>
      <span class="btn btn-outline-primary">
        <%= link_to t('announcements.buttons.sign_in'), new_user_session_path %>
      </span>
      <span class="btn btn-outline-primary">
        <%= link_to t('announcements.buttons.sign_up'), new_user_registration_path %>
      </span>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projectads</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './layouts/header' %>
    <ul class="locales">
      <li><%= link_to 'English', url_for(locale: :en) %></li>
      <li><%= link_to 'Русский', url_for(locale: :ru) %></li>
    </ul>
    <div class="container">
      <%= yield %>
    </div>
    <%= render './layouts/footer' %>
  </body>
</html>

app/views/users/announcements.html.erb
<h2><%= t('announcements.titles.user_announcements') %></h2> 
<% if current_user.announcements.count != 0 %>
  <% @announcements.each do |announcement| %>
    <div class="media">
      <div class="product-img">
        <%= image_tag(announcement.image) if announcement.image.attached? %>
      </div>
      <div class="media-body">
        <%= announcement.title %><br>
        <%= announcement.content %><br>
        <%= t("announcements.types.#{announcement.announcement_type.downcase}") %><br>
        <%= announcement.user_id %><br>
        <%= t("announcements.status.#{announcement.status}") %><br>
        <%= link_to t('announcements.buttons.show'), announcement %>

        <% if can? :index, @announcement %>
          <%= link_to t('announcements.buttons.edit'), edit_announcement_path(announcement) %>
        <% end %>

        <% if can? :destroy, @announcement %>
          <%= link_to t('announcements.buttons.destroy'), announcement, method: :delete, data: { confirm: t('confirm_messages.confirm_delete') } %>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <p><%= t('flashes.no_posts') %></p>
<% end %>

<%= link_to t('announcements.buttons.back'), announcements_path %>